version: '3'
services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/airflow/dags
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow
    depends_on:
      - postgres
    command: ["bash", "-c", "poetry install --no-dev && airflow web"]

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}